*-----------------------------------------------------------------------------
* <Rating>0</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE IDI.IN.GET.FT.STAN(Y.RET.VALUE)
**ROUTINE TO GET TRACE NUMBER TRANSACTION FOR EXTRACT FILE RECON ATM(ATILHM-20150430)
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.IDIH.WS.DATA.FT.MAP
    $INSERT I_IDIB.GEN.FT.MAP.DATA.COMMON
*DEBUG
    Y.RET.VALUE = Y.IN.STAN

    RETURN
END


