**CREATED FOR GET FT FOR EXTRACT FILE CHARGES RECON ATM(ATILHM-20150430)
*-----------------------------------------------------------------------------
* <Rating>0</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE IDI.IN.GET.FT.TRN.TYP(Y.RET.VALUE)
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.IDIH.WS.DATA.FT.MAP
    $INSERT I_IDI.GET.DATA.FT.MAP.COMMON


    Y.RET.VALUE = Y.NO.FT

    RETURN

END



